"""Every county inside the radius, with where its tax sale information lives.

Georgia tax sales are held on the first Tuesday of the month at the courthouse (or another posted location), usually
run by the Tax Commissioner acting as ex officio sheriff. Each county publishes different things, so `fetch` points to a
parser only where the county posts parcel-level data that can be read automatically.
"""
import counties_metro as M
import counties_outer as O

TC = "Tax Commissioner"
QP = "https://qpublic.schneidercorp.com/"

COUNTIES = [
    dict(name="Fulton", run="Sheriff", page="https://fcsoga.org/tax-sales/", schedule="First Tuesday monthly, 10am to 4pm, 136 Pryor St SW, Atlanta",
         excess="https://fcsoga.org/help/how-do-i-request-a-list-of-excess-tax-funds/", parcel="https://iaspublicaccess.fultoncountyga.gov/", fetch=M.fulton,
         note="Sale lists are scanned images, read here with OCR. Results and excess funds are not published (excess list by open records request only)."),
    dict(name="DeKalb", run=TC, page="https://dekalbtaxga.gov/property-tax/tax-sales/", schedule="First Tuesday monthly, 9am to 4pm, DeKalb County Courthouse, Decatur",
         excess="https://dekalbtaxga.gov/wp-content/uploads/Excess-Funds-List.pdf", parcel="https://publicaccess.dekalbtaxga.gov/", fetch=M.dekalb,
         note="Only the upcoming sale list is posted. Prior sales come from the excess funds list (parcels that sold above what was owed)."),
    dict(name="Cobb", run=TC, page="https://www.cobbtax.gov/property/tax_sale/index.php", schedule="Selected first Tuesdays (2026: May 5 and Nov 3), Superior Court Plaza, Marietta",
         excess="https://www.cobbtax.gov/property/tax_sale/index.php", parcel="https://www.cobbassessor.org/", fetch=M.cobb,
         note="The November 3, 2026 list is posted about four weeks before the sale. Prior sales come from the excess funds list, which names the buyer."),
    dict(name="Clayton", run=TC, page="https://publicaccess.claytoncountyga.gov/content/home_commissioner.htm", schedule="First Tuesday monthly, Clayton County Courthouse, Jonesboro",
         excess="https://publicaccess.claytoncountyga.gov/content/PDF/DQ759GA.pdf", parcel="https://publicaccess.claytoncountyga.gov/", fetch=M.clayton,
         note="Monthly sale lists include fair market value and the opening (cry-out) bid. Results are not published; the excess funds list shows which parcels sold above the bid."),
    dict(name="Henry", run=TC, page="https://www.henrycountytax.com/244/TAX-SALE-LIST", schedule="First Tuesday, 140 Henry Pkwy, McDonough (judicial in rem sales)",
         excess="https://henrycountytax.com/239/EXCESS-FUNDS", parcel=QP, fetch=M.henry, note="Only the current list is posted; amounts owed are behind per-parcel payoff links."),
    dict(name="Douglas", run=TC, page="https://www.douglastax.org/property-tax-sales", schedule="First Tuesday, Tax Commissioner's Office, 6200 Fairburn Rd, Douglasville",
         excess="https://www.douglastax.org/property-tax-sales", parcel=QP, fetch=O.douglas, note="Lists are published as newspaper legal ads. Results and excess funds are not posted online."),
    dict(name="Gwinnett", run=TC, page="https://www.gwinnetttaxcommissioner.com/property-tax/delinquent_tax/tax-liens-tax-sales", schedule="First Tuesday (several times a year), Gwinnett Justice and Administration Center, Lawrenceville",
         excess="https://www.gwinnetttaxcommissioner.com/property-tax/delinquent_tax/tax-liens-tax-sales", parcel="https://www.gwinnettassessor.manatron.com/", fetch=M.gwinnett,
         note="Full results with winning bids and buyers are published for every sale from 2021 through early 2026."),
    dict(name="Rockdale", run=TC, page="https://rockdaletaxoffice.org/tax-sale-properties/", schedule="First Tuesday, Rockdale County Courthouse, Conyers",
         excess="https://rockdaletaxoffice.org/property-tax-sales", parcel=QP, fetch=M.rockdale, note="Current list is posted as a spreadsheet. The excess funds list is a scanned image and results are not posted."),
    dict(name="Fayette", run=TC, page="https://www.fayettecountypay.com/tax-sales.html", schedule="First Tuesday when scheduled, 10am to 4pm, Fayette County Courthouse steps, Fayetteville",
         excess=None, parcel=QP, fetch=O.fayette, note="The county posts a list of the properties that sold at its most recent sale (December 2, 2025), with winning bid and buyer."),
    dict(name="Paulding", run=TC, page="https://www.pauldingcountytax.com/tax-sales.html", schedule="First Tuesday when scheduled, Paulding County Courthouse, Dallas",
         excess="https://www.paulding.gov/1054/Previously-Advertised-Parcel-List", parcel=QP, fetch=None, note="No sale is posted right now and the county site blocks automated access. Check the county links."),
    dict(name="Coweta", run=TC, page="https://www.cowetataxcom.com/tax-sales.html", schedule="About once a year (August or September), first Tuesday, Coweta County Courthouse, Newnan",
         excess="https://www.cowetataxcom.com/resources/sites/cowetacountyga/docs/EXCESS%20FUNDS%20LIST.pdf", parcel=QP, fetch=O.coweta,
         note="The next sale is planned for August 2027. Prior sales come from the excess funds list, which includes the minimum bid, sale price and buyer."),
    dict(name="Cherokee", run=TC, page="https://www.cherokeecountytax.com/tax-sales.html", schedule="First Tuesday when scheduled, 90 North Street, Canton",
         excess="https://www.weissman.law/specialties/excess-tax-funds/", parcel=QP, fetch=None, note="The county posts only sale dates, not parcel lists. Excess funds are handled by Weissman Law."),
    dict(name="Walton", run=TC, page="https://tax.waltoncountypay.com/tax-sales.html", schedule="First Tuesday as needed, Government Building, 303 S Hammond Dr, Monroe",
         excess="https://tax.waltoncountypay.com/tax-sales.html", parcel="https://qpublic.net/ga/walton/", fetch=O.walton,
         note="Sale lists are posted as spreadsheets. The excess funds list includes sale price and buyer."),
    dict(name="Newton", run=TC, page="https://newtoncountytax.com/property_tax/tax-sales/", schedule="First Tuesday, 10am, Newton County Courthouse, Covington",
         excess="https://www.weissman.law/specialties/excess-tax-funds/", parcel=QP, fetch=None, note="The county website puts a captcha on every file, so lists can't be read automatically. Use the county link for the October 6, 2026 list."),
    dict(name="Forsyth", run=TC, page="https://forsythcountytax.com/tax-sales-excess-funds/", schedule="First Tuesday as needed, Forsyth County Courthouse steps, Cumming",
         excess="https://forsythcountytax.com/excess-funds-listing-2/", parcel=QP, fetch=O.forsyth, note="No list is posted now. Prior sales come from the excess funds table, which includes purchase price and amount due."),
    dict(name="Carroll", run=TC, page="https://carrollcountygatax.com/tax-sales-2/", schedule="First Tuesday when scheduled (next: April 6, 2027), Carroll County Courthouse, Carrollton",
         excess="https://carrollcountygatax.com/wp-content/uploads/2026/09/EXCESS_FUNDS_LIST-1.xls", parcel=QP, fetch=O.carroll,
         note="After each sale the county reposts its legal ad marked SOLD FOR or NO BID, so results are available for several sales."),
    dict(name="Spalding", run=TC, page="https://spaldingcountytaxga.com/tax-sales/", schedule="First Tuesday monthly, 411 E Solomon St, Griffin",
         excess=None, parcel=QP, fetch=O.spalding, note="Most monthly lists are scanned images; only the spreadsheet versions are read here. Results and excess funds are not posted."),
    dict(name="Bartow", run=TC, page="https://tax.bartowpay.com/tax-sales.html", schedule="Once a year in June, first Tuesday, Bartow County Courthouse, Cartersville",
         excess="https://www.bartowcountyga.gov/departments/tax_commissioner/index.php", parcel=QP, fetch=None, note="No list is posted now. The overage file (buyers and overage only) is a rotating SharePoint link."),
    dict(name="Butts", run=TC, page="https://www.buttscountytax.com/tax-sales.html", schedule="First Tuesday when scheduled, Jackson", excess=None, parcel="https://www.qpublic.net/ga/butts/", fetch=None,
         note="No sale or excess funds list is posted."),
    dict(name="Barrow", run=TC, page="https://www.barrowgatax.org/tax-sales.html", schedule="First Tuesday when scheduled, Winder", excess="https://www.weissman.law/specialties/excess-tax-funds/", parcel=QP, fetch=None,
         note="Parcels run only in the Barrow Journal legal ads four weeks before a sale."),
    dict(name="Hall", run=TC, page="https://hallcountytax.org/property/tax-sale/", schedule="First Tuesday when scheduled, Gainesville", excess="https://hallcountytax.org/property/excess-funds/", parcel=QP, fetch=None,
         note="The Hall County tax site blocks automated access (Cloudflare). Use the county links."),
    dict(name="Polk", run=TC, page="https://www.polkcountypay.com/tax-sales.html", schedule="First Tuesday (2026: Oct 6 and Nov 3), Cedartown",
         excess="https://www.polkcountypay.com/resources/sites/polkcountyga/docs/EXCESS_FUNDS_LIST_UPDATED_10172024.xls", parcel=QP, fetch=O.polk,
         note="Current list is a spreadsheet with amounts owed. The excess list includes sale prices for 2018 to 2023."),
    dict(name="Meriwether", run=TC, page="https://www.meriwethertax.com/tax-sales.html", schedule="First Tuesday when scheduled, Greenville",
         excess="https://www.meriwethertax.com/excess_funds.html", parcel=QP, fetch=O.meriwether, note="Sale lists include amounts due. The excess funds list includes purchase price and buyer."),
    dict(name="Haralson", run=TC, page="https://haralsoncountyga.governmentwindow.com/", schedule="First Tuesday when scheduled, Buchanan", excess=None, parcel="https://www.qpublic.net/ga/haralson/", fetch=None,
         note="The tax site blocks automated access. Use the county links."),
    dict(name="Pike", run=TC, page="https://tax.pikecountypay.com/tax-sales.html", schedule="No schedule published", excess=None, parcel=QP, fetch=None, note="No sale, list or excess funds are posted."),
    dict(name="Jasper", run=TC, page="https://jaspercountygatax.com/tax-sales/", schedule="Last sale June 2, 2026, Monticello", excess="https://jaspercountygatax.com/excess-funds-from-prior-tax-sales/", parcel=QP, fetch=None,
         note="Sale dates are announced but no parcel lists are posted."),
    dict(name="Lamar", run=TC, page="https://tax.lamarcountypay.com/tax-sales.html", schedule="No schedule published", excess=None, parcel=QP, fetch=None, note="No sale, list or excess funds are posted."),
    dict(name="Jackson", run=TC, page="https://jacksoncountygatax.com/", schedule="First Tuesday when scheduled, Jefferson", excess=None, parcel=QP, fetch=O.jackson,
         note="The only results file online is from March 2017. Recent sales are not posted."),
    dict(name="Dawson", run=TC, page="https://dawsoncountytax.com/", schedule="First Tuesday when scheduled (next: October 6, 2026), Dawsonville", excess=None, parcel=QP, fetch=O.dawson,
         note="The October 2026 sale is personal property and mobile homes only. The excess funds list (with bid amounts) covers 2016 to 2020."),
    dict(name="Morgan", run=TC, page="https://www.morgangatax.org/tax-sales.html", schedule="No schedule published", excess=None, parcel=QP, fetch=None,
         note="No sale is posted. The county does not release excess funds information to third parties."),
    dict(name="Heard", run=TC, page="https://www.heardcountyga.com/taxCommissioners.html", schedule="When scheduled, Franklin", excess=None, parcel=QP, fetch=O.heard, note="The latest posted list is from the November 2025 sale."),
    dict(name="Monroe", run=TC, page="https://www.monroecountytax.com/tax-sales.html", schedule="No schedule published", excess=None, parcel=QP, fetch=None, note="No sale or list is posted."),
    dict(name="Pickens", run=TC, page="https://pickensgatax.com/tax-sales/", schedule="Usually once a year in February, Jasper", excess="https://pickensgatax.com/tax-sales/", parcel="http://www.qpublic.net/ga/pickens", fetch=O.pickens,
         note="The excess funds spreadsheet includes starting bid and selling amount back to 2012."),
    dict(name="Oconee", run=TC, page="https://www.oconeecountypay.com/tax-sales.html", schedule="Next sale tentatively March 2027, Watkinsville", excess="https://images-governmentwindow.s3.amazonaws.com/resources/sites/oconeecountyga/docs/Excess_Funds.pdf",
         parcel=QP, fetch=None, note="No parcel lists are posted and no excess funds are currently held."),
    dict(name="Floyd", run=TC, page="https://www.floydcountytax.com/tax-sales.html", schedule="First Tuesday, May through September, Rome", excess=None, parcel=QP, fetch=O.floyd,
         note="Weekly legal ads are archived for every sale month. They list parcels and owners but not amounts owed or results."),
    dict(name="Troup", run=TC, page="https://troupcountytax.com/", schedule="First Tuesday monthly (about April to October), 100 Ridley Ave, LaGrange",
         excess="https://troupcountytax.com/", parcel=QP, fetch=O.troup, note="Monthly lists include the opening bid. Results are not posted; the excess funds list shows parcels that sold above it."),
    dict(name="Gordon", run=TC, page="https://gordoncountytax.com/tax-sales/", schedule="No sales at this time", excess=None, parcel="https://gordonproperty.assurancegov.com/", fetch=None,
         note="No sales, lists or excess funds are posted."),
    dict(name="Clarke", label="Athens-Clarke", run="Tax Commissioner (ex officio sheriff)", page="https://www.accgov.com/1719/Tax-Sales", schedule="First Tuesday when scheduled, 10am, Athens-Clarke County Courthouse",
         excess="https://accgov.com/3910/Excess-Funds", parcel=QP, fetch=O.clarke, note="No sale on October 6, 2026. The excess funds list includes the winning bid for 2020 to 2025 sales."),
    dict(name="Lumpkin", run=TC, page="https://www.lumpkincountytax.com/news.html", schedule="September, first Tuesday, Dahlonega", excess="https://www.lumpkincountytax.com/news.html", parcel=QP, fetch=O.lumpkin,
         note="Lists appear only in Dahlonega Nugget legal notices. The excess funds list shows prior sales with overage."),
    dict(name="Upson", run=TC, page="https://www.upsoncountyga.org/202/Office-of-the-Tax-Commissioner", schedule="First Tuesday when scheduled, Thomaston-Upson Civic Center", excess=None, parcel=QP, fetch=None,
         note="Lists appear only as Upson Beacon legal notices. No results or excess funds are posted."),
]
